markdown: redcarpet
pygments: true
permalink: /:title.html
timezone: Asia/Chongqing

url: http://peqiu.com/blog

redcarpet:
  extensions: [strikethrough, tables]

blog:
    name:                                                # 博客名称
    description:                                         # 博客描述
    title:                                               # 网页标题
    url:                                                 # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:                                                # 作者名称
    email:                                               # 邮箱地址
    weibo:                                               # 微博地址
    github:                                              # GitHub地址
    logo:                                                # logo地址
    douban:
        name:   Hippy                                         # 豆瓣地址名称
        key:   0dcabc8a7a7624272960359f6f626c75                                          # 豆瓣API Key
